<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find rm_description)/urdf/common/mecanum_wheel.urdf.xacro"/>

    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="wheel_track" value="0.392"/>
    <xacro:property name="wheel_base" value="0.404"/>
    <xacro:property name="wheel_offset_z" value="0.000031"/>

    <xacro:macro name="chassis" params="roller_type">

        <link name="base_link">
            <inertial>
                <mass value="8.44"/>
                <origin xyz="-0.000578 0.00437 0.0620"/>
                <inertia ixx="2.081e-1" ixy="5.195e-3" ixz="2.242e-3" iyy="2.784e-1"
                         iyz="2.494e-3" izz="3.521e-1"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 .001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>


        <xacro:mecanum_wheel prefix="left_front" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="right_front" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="left_back" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="right_back" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"/>
        <xacro:wheel_transmission prefix="left_front" mechanical_reduction="19.2032"/>
        <xacro:wheel_transmission prefix="right_front" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="left_back" mechanical_reduction="19.2032"/>
        <xacro:wheel_transmission prefix="right_back" mechanical_reduction="-19.2032"/>

    </xacro:macro>

</robot>
